"""Initial migration

Revision ID: 3cd29cb961e8
Revises: 
Create Date: 2026-06-18 11:52:08.798284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd29cb961e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Operator', 'Tech_Admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('max_in_use', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_code', sa.String(length=255), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_code')
    )
    op.create_table('applicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('current_zone_id', sa.Integer(), nullable=True),
    sa.Column('current_machine_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('in_use', 'on_rack', 'none', name='applicatorstate'), nullable=False),
    sa.ForeignKeyConstraint(['current_machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('block_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicator_id'], ['applicators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicator_id'], ['applicators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_logs')
    op.drop_table('block_logs')
    op.drop_table('applicators')
    op.drop_table('machines')
    op.drop_table('zones')
    op.drop_table('users')
    # ### end Alembic commands ###
