"""add operator_code

Revision ID: 60423c9e5de2
Revises: f381fe8f3005
Create Date: 2026-06-18 18:02:15.593732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60423c9e5de2'
down_revision: Union[str, Sequence[str], None] = 'f381fe8f3005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('operator_code', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['operator_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'operator_code')
    # ### end Alembic commands ###
